### ISSUE TITLE
yii2 advanced application issue ?

### ISSUE THREAD

**Issue by paskuale75** [NullRefExcep/yii2-category#3]
PHP Compile Error 'yii\base\ErrorException' with message 'nullref\core\components\ModuleInstaller::addToConfig(): Failed opening required '/var/www/AppName/console/config/installed_modules.php' (include_path='.:/usr/share/php')'

**Comment by ZAYEC77** [comment]
Hello
I think you could try to create file like this https://github.com/NullRefExcep/yii2-boilerplate/blob/master/src/config/installed_modules.php
in needed location.

**Comment by ZAYEC77** [comment]
Also, you can add module manually to your common config and run migration, without run installation command. It's acceptable too.

**Comment by paskuale75** [comment]
Ok, many thanks ;)
