### ISSUE TITLE
I cannot install this extension

### ISSUE THREAD

**Issue by ghost** [NullRefExcep/yii2-category#6]
yii2 advanced 2.0.14 php7.1.13

$  composer require --prefer-dist nullref/yii2-category "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nullref/yii2-category dev-master requires nullref/yii2-core dev-master -> satisfiable by nullref/yii2-core[dev-master].
    - Conclusion: don't install nullref/yii2-core dev-master
    - nullref/yii2-admin dev-master requires nullref/yii2-core >=0.0.3 -> satisfiable by nullref/yii2-core[dev-master, v0.0.3].
    - nullref/yii2-category v0.0.1 requires nullref/yii2-admin dev-master -> satisfiable by nullref/yii2-admin[dev-master].
    - Conclusion: remove symfony/finder v4.1.4
    - Installation request for nullref/yii2-category * -> satisfiable by nullref/yii2-category[dev-master, v0.0.1].
    - Conclusion: don't install symfony/finder v4.1.4
    - nullref/yii2-core v0.0.3 requires symfony/finder ^3.1 -> satisfiable by symfony/finder[3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.
8, v3.1.9, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12
, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12
, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/finder[3.1.x-dev, v4.1.4].
    - Can only install one of: symfony/finder[3.2.x-dev, v4.1.4].
    - Can only install one of: symfony/finder[3.3.x-dev, v4.1.4].
    - Can only install one of: symfony/finder[3.4.x-dev, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.0, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.0-BETA1, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.0-RC1, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.1, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.10, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.2, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.3, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.4, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.5, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.6, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.7, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.8, v4.1.4].
    - Can only install one of: symfony/finder[v3.1.9, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.0, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.0-BETA1, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.0-RC1, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.0-RC2, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.1, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.10, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.11, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.12, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.13, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.14, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.2, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.3, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.4, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.5, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.6, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.7, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.8, v4.1.4].
    - Can only install one of: symfony/finder[v3.2.9, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.0, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.0-BETA1, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.0-RC1, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.1, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.10, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.11, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.12, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.13, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.14, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.15, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.16, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.17, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.18, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.2, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.3, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.4, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.5, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.6, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.7, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.8, v4.1.4].
    - Can only install one of: symfony/finder[v3.3.9, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-BETA1, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-BETA2, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-BETA3, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-BETA4, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-RC1, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.0-RC2, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.1, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.10, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.11, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.12, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.13, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.14, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.15, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.2, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.3, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.4, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.5, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.6, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.7, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.8, v4.1.4].
    - Can only install one of: symfony/finder[v3.4.9, v4.1.4].
    - Installation request for symfony/finder (locked at v4.1.4) -> satisfiable by symfony/finder[v4.1.4].

Installation failed, reverting ./composer.json to its original content.

How do I deal with this problem?

**Comment by ZAYEC77** [comment]
Hello, please attache your composer.json file

**Comment by ZAYEC77** [comment]
@thinkwcz please, try again
I have updated package

**Comment by ghost** [comment]
@ZAYEC77
composer.json
 {
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "dektrium/yii2-user": "^0.9.14"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
